twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/src/Infrastructure/Presentation/Web/Template'
    globals:
        socketUrl: '%env(SOCKET_URL)%'
when@test:
    twig:
        strict_variables: true
