twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/src/Infrastructure/Presentation/Web/Template'
    globals:
        socketUrl: '%env(SOCKET_URL)%'
    form_themes:
        - 'shared/form/theme.html.twig'
when@test:
    twig:
        strict_variables: true
