services:
  nginx:
    image: nginx:latest
    container_name: help_nginx
    ports:
      - "8011:80"
    volumes:
      - ../../sources:/app:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - help_network

  php:
    image: php:8.3-fpm
    container_name: help_php
    env_file:
      - ../.env.local
    volumes:
      - ../../sources:/app:rw
      - ./entrypoint.sh:/entrypoint.sh:ro
    working_dir: /app
    entrypoint: ["/entrypoint.sh"]
    command: ["php-fpm"]
    networks:
      - help_network

  db:
    image: mysql:8.0
    container_name: help_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../../data/mysql:/var/lib/mysql
    networks:
      - help_network
    ports:
      - "8016:3306"

  redis:
    image: redis:latest
    container_name: help_redis
    restart: always
    networks:
      - help_network
    ports:
      - "8017:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ../../data/redis:/data

networks:
  help_network:
    driver: bridge
