# config/routes.yaml

api:
    resource: ../src/Infrastructure/Presentation/Api/Controller
    type: attribute
    prefix: /api/

manager:
    resource: ../src/Infrastructure/Presentation/Web/Controller/Manager
    type: attribute
    prefix: /manager

customer:
    resource: ../src/Infrastructure/Presentation/Web/Controller/Customer
    type: attribute
    prefix: /customer

public:
    resource: ../src/Infrastructure/Presentation/Web/Controller/Public
    type: attribute
    prefix: /
